import type { Diagram, Dialect, Table, Column } from "./types";

function typeFor(type: string, dialect: Dialect): string {
  const t = type.toLowerCase();
  if (dialect === "mysql") {
    const map: Record<string, string> = {
      serial: "INT AUTO_INCREMENT",
      uuid: "CHAR(36)",
      varchar: "VARCHAR(255)",
      text: "TEXT",
      boolean: "TINYINT(1)",
      timestamp: "DATETIME",
      jsonb: "JSON",
      numeric: "DECIMAL(10,2)",
      integer: "INT",
      bigint: "BIGINT",
    };
    return map[t] ?? type.toUpperCase();
  }
  if (dialect === "sqlite") {
    const map: Record<string, string> = {
      serial: "INTEGER",
      uuid: "TEXT",
      varchar: "TEXT",
      boolean: "INTEGER",
      timestamp: "TEXT",
      jsonb: "TEXT",
      json: "TEXT",
      numeric: "REAL",
      bigint: "INTEGER",
    };
    return map[t] ?? type.toUpperCase();
  }
  // postgres
  const map: Record<string, string> = {
    varchar: "VARCHAR(255)",
    numeric: "NUMERIC(10,2)",
  };
  return map[t] ?? type.toUpperCase();
}

function quote(name: string, dialect: Dialect): string {
  if (dialect === "mysql") return `\`${name}\``;
  return `"${name}"`;
}

function columnLine(col: Column, dialect: Dialect): string {
  const parts: string[] = [quote(col.name, dialect), typeFor(col.type, dialect)];
  if (!col.isNullable) parts.push("NOT NULL");
  if (col.isUnique && !col.isPrimary) parts.push("UNIQUE");
  if (col.defaultValue) parts.push(`DEFAULT ${col.defaultValue}`);
  return "  " + parts.join(" ");
}

function tableSql(table: Table, diagram: Diagram): string {
  const dialect = diagram.dialect;
  const lines: string[] = table.columns.map((c) => columnLine(c, dialect));

  const pks = table.columns.filter((c) => c.isPrimary);
  if (pks.length > 0) {
    lines.push(`  PRIMARY KEY (${pks.map((c) => quote(c.name, dialect)).join(", ")})`);
  }

  // foreign keys where this table is the source
  const fks = diagram.relationships.filter((r) => r.sourceTableId === table.id);
  for (const fk of fks) {
    const targetTable = diagram.tables.find((t) => t.id === fk.targetTableId);
    const sourceCol = table.columns.find((c) => c.id === fk.sourceColumnId);
    const targetCol = targetTable?.columns.find((c) => c.id === fk.targetColumnId);
    if (targetTable && sourceCol && targetCol) {
      lines.push(
        `  FOREIGN KEY (${quote(sourceCol.name, dialect)}) REFERENCES ${quote(
          targetTable.name,
          dialect,
        )} (${quote(targetCol.name, dialect)})`,
      );
    }
  }

  return `CREATE TABLE ${quote(table.name, dialect)} (\n${lines.join(",\n")}\n);`;
}

export function generateSql(diagram: Diagram): string {
  if (diagram.tables.length === 0) {
    return "-- Add a table to generate SQL";
  }
  const header = `-- ${diagram.name}\n-- Generated by OpenFlowDB (${diagram.dialect})\n`;
  const body = diagram.tables.map((t) => tableSql(t, diagram)).join("\n\n");
  return `${header}\n${body}\n`;
}
